DEBUG 2017-05-12 11:44:43,699: 	 Executing command: 'submit'
DEBUG 2017-05-12 11:44:43,699: 	 Found CRAB cache file /afs/desy.de/user/z/zoiirene/.crab3
DEBUG 2017-05-12 11:44:43,706: 	 Checking credentials
DEBUG 2017-05-12 11:44:43,706: 	 Found proxy file /tmp/x509up_u28517
DEBUG 2017-05-12 11:44:43,706: 	 Getting proxy life time left
DEBUG 2017-05-12 11:44:44,210: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u28517 -timeleft
 output : 38600

 error: 
 retcode : 0
DEBUG 2017-05-12 11:44:44,913: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u28517 -actimeleft
 output : 38599

 error: 
 retcode : 0
DEBUG 2017-05-12 11:44:44,913: 	 Proxy valid for 10:43:20 hours
INFO 2017-05-12 11:44:44,914: 	 Will use CRAB configuration file crab_ntupleRationToWW.py
DEBUG 2017-05-12 11:44:44,914: 	 Loading CRAB configuration file.
ERROR 2017-05-12 11:44:44,948: 	 Error while loading CRAB configuration:
No module named DasQuery
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2017-05-12 11:44:44,948: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1705.patch3/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1705.patch3/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1705.patch3/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1705.patch3/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 298, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1705.patch3/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 84, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Error while loading CRAB configuration:
No module named DasQuery
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
DEBUG 2017-05-12 11:49:56,087: 	 Executing command: 'submit'
DEBUG 2017-05-12 11:49:56,088: 	 Found CRAB cache file /afs/desy.de/user/z/zoiirene/.crab3
DEBUG 2017-05-12 11:49:56,094: 	 Checking credentials
DEBUG 2017-05-12 11:49:56,094: 	 Found proxy file /tmp/x509up_u28517
DEBUG 2017-05-12 11:49:56,094: 	 Getting proxy life time left
DEBUG 2017-05-12 11:49:56,497: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u28517 -timeleft
 output : 43188

 error: 
 retcode : 0
DEBUG 2017-05-12 11:49:56,900: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u28517 -actimeleft
 output : 43188

 error: 
 retcode : 0
DEBUG 2017-05-12 11:49:56,901: 	 Proxy valid for 11:59:48 hours
INFO 2017-05-12 11:49:56,901: 	 Will use CRAB configuration file crab_ntupleRationToWW.py
DEBUG 2017-05-12 11:49:56,901: 	 Loading CRAB configuration file.
ERROR 2017-05-12 11:49:56,920: 	 Error while loading CRAB configuration:
No module named DasQuery
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2017-05-12 11:49:56,921: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1705.patch3/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1705.patch3/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1705.patch3/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1705.patch3/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 298, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1705.patch3/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 84, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Error while loading CRAB configuration:
No module named DasQuery
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
DEBUG 2017-05-12 12:13:45,899: 	 Executing command: 'submit'
DEBUG 2017-05-12 12:13:45,899: 	 Found CRAB cache file /afs/desy.de/user/z/zoiirene/.crab3
DEBUG 2017-05-12 12:13:45,905: 	 Checking credentials
DEBUG 2017-05-12 12:13:45,905: 	 Found proxy file /tmp/x509up_u28517
DEBUG 2017-05-12 12:13:45,905: 	 Getting proxy life time left
DEBUG 2017-05-12 12:13:46,408: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u28517 -timeleft
 output : 41758

 error: 
 retcode : 0
DEBUG 2017-05-12 12:13:46,811: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u28517 -actimeleft
 output : 41758

 error: 
 retcode : 0
DEBUG 2017-05-12 12:13:46,811: 	 Proxy valid for 11:35:58 hours
INFO 2017-05-12 12:13:46,811: 	 Will use CRAB configuration file crab_ntupleRationToWW.py
DEBUG 2017-05-12 12:13:46,811: 	 Loading CRAB configuration file.
DEBUG 2017-05-12 12:13:48,950: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2017-05-12 12:13:48,951: 	 Working area '/nfs/dust/cms/user/zoiirene/CMSSW_8_0_24_patch1/src/UHH2/scripts/crab/crab_ntupleRadionToWW/crab_VBF_RadionToWW_narrow_M-2000_13TeV-madgraph' already exists 
Please change the requestName in the config file
ERROR 2017-05-12 12:13:48,951: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1705.patch3/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1705.patch3/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1705.patch3/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1705.patch3/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 302, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1705.patch3/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 394, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/nfs/dust/cms/user/zoiirene/CMSSW_8_0_24_patch1/src/UHH2/scripts/crab/crab_ntupleRadionToWW/crab_VBF_RadionToWW_narrow_M-2000_13TeV-madgraph' already exists 
Please change the requestName in the config file
DEBUG 2017-05-12 12:14:29,720: 	 Executing command: 'submit'
DEBUG 2017-05-12 12:14:29,720: 	 Found CRAB cache file /afs/desy.de/user/z/zoiirene/.crab3
DEBUG 2017-05-12 12:14:29,726: 	 Checking credentials
DEBUG 2017-05-12 12:14:29,726: 	 Found proxy file /tmp/x509up_u28517
DEBUG 2017-05-12 12:14:29,726: 	 Getting proxy life time left
DEBUG 2017-05-12 12:14:30,128: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u28517 -timeleft
 output : 41714

 error: 
 retcode : 0
DEBUG 2017-05-12 12:14:30,532: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u28517 -actimeleft
 output : 41714

 error: 
 retcode : 0
DEBUG 2017-05-12 12:14:30,532: 	 Proxy valid for 11:35:14 hours
INFO 2017-05-12 12:14:30,532: 	 Will use CRAB configuration file crab_ntupleRationToWW.py
DEBUG 2017-05-12 12:14:30,532: 	 Loading CRAB configuration file.
DEBUG 2017-05-12 12:14:32,613: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2017-05-12 12:14:32,614: 	 Working area '/nfs/dust/cms/user/zoiirene/CMSSW_8_0_24_patch1/src/UHH2/scripts/crab/crab_ntupleRadionToWW/crab_VBF_RadionToWW_narrow_M-2000_13TeV-madgraph' already exists 
Please change the requestName in the config file
ERROR 2017-05-12 12:14:32,614: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1705.patch3/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1705.patch3/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1705.patch3/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1705.patch3/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 302, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1705.patch3/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 394, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/nfs/dust/cms/user/zoiirene/CMSSW_8_0_24_patch1/src/UHH2/scripts/crab/crab_ntupleRadionToWW/crab_VBF_RadionToWW_narrow_M-2000_13TeV-madgraph' already exists 
Please change the requestName in the config file
DEBUG 2017-05-12 12:14:56,107: 	 Executing command: 'submit'
DEBUG 2017-05-12 12:14:56,107: 	 Found CRAB cache file /afs/desy.de/user/z/zoiirene/.crab3
DEBUG 2017-05-12 12:14:56,113: 	 Checking credentials
DEBUG 2017-05-12 12:14:56,113: 	 Found proxy file /tmp/x509up_u28517
DEBUG 2017-05-12 12:14:56,113: 	 Getting proxy life time left
DEBUG 2017-05-12 12:14:56,616: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u28517 -timeleft
 output : 41688

 error: 
 retcode : 0
DEBUG 2017-05-12 12:14:57,019: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u28517 -actimeleft
 output : 41687

 error: 
 retcode : 0
DEBUG 2017-05-12 12:14:57,019: 	 Proxy valid for 11:34:48 hours
INFO 2017-05-12 12:14:57,019: 	 Will use CRAB configuration file crab_ntupleRationToWW.py
DEBUG 2017-05-12 12:14:57,020: 	 Loading CRAB configuration file.
DEBUG 2017-05-12 12:14:59,162: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2017-05-12 12:14:59,163: 	 Working area '/nfs/dust/cms/user/zoiirene/CMSSW_8_0_24_patch1/src/UHH2/scripts/crab/crab_ntupleRadionToWW/crab_VBF_RadionToWW_narrow_M-2000_13TeV-madgraph' already exists 
Please change the requestName in the config file
ERROR 2017-05-12 12:14:59,163: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1705.patch3/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1705.patch3/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1705.patch3/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1705.patch3/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 302, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1705.patch3/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 394, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/nfs/dust/cms/user/zoiirene/CMSSW_8_0_24_patch1/src/UHH2/scripts/crab/crab_ntupleRadionToWW/crab_VBF_RadionToWW_narrow_M-2000_13TeV-madgraph' already exists 
Please change the requestName in the config file
